name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      matrix:
        solc_version: [0.8.20]
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Foundry Build
        uses: actions/cache@v3
        with:
          path: ~/.foundry
          key: foundry-cache-${{ runner.os }}-${{ hashFiles('foundry.toml') }}
          restore-keys: |
            foundry-cache-${{ runner.os }}-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Set Solidity Version
        run: forge config set solc ${solc_version}

      - name: Run Forge Build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge Tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge Coverage
        continue-on-error: true
        run: |
          forge coverage --report lcov
        id: coverage

      - name: Run Slither Analysis
        run: |
          pip install slither-analyzer
          slither .
        id: slither

      - name: Run Solhint
        run: |
          npm install -g solhint
          solhint 'src/**/*.sol'
        id: lint
