name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      matrix:
        solc_version: [0.8.24]
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clear cache
        run: |
          rm -rf ~/.foundry
          mkdir -p ~/.foundry

      - name: Cache Foundry Build
        uses: actions/cache@v3
        with:
          path: ~/.foundry
          key: foundry-cache-${{ runner.os }}-${{ hashFiles('foundry.toml') }}-${{ matrix.solc_version }}-v1
          restore-keys: |
            foundry-cache-${{ runner.os }}-

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Set and Verify Solidity Version
        run: |
          forge config set solc ${solc_version}
          forge config | grep solc

      - name: Run Forge Build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge Tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge Coverage
        continue-on-error: true
        run: |
          forge coverage --report lcov
        id: coverage

      - name: Run Slither Analysis
        continue-on-error: true
        run: |
          pip install slither-analyzer
          slither . --config-file slither.config.json
        id: slither

      - name: Install and Run Solhint
        run: |
          npm install -g solhint
          solhint 'src/**/*.sol'
        id: lint
